- name: install packages (pacman)
  pacman:
    name:
      - wofi
    state: present
  become: yes

- name: install packages (aur)
  kewlfft.aur.aur:
    name: 
      - gnome-shell-extension-pop-shell-bin
      - gnome-shell-extension-just-perfection-desktop-git
      - gnome-shell-extension-emoji-selector-git
      - gnome-shell-extension-caffeine-git
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-sound-output-device-chooser-git
      - gnome-shell-extension-simply-workspaces-git
    state: present

# - name: Install simply workspaces
#  git:
#    repo: https://github.com/andyrichardson/simply-workspaces.git 
#    dest: /home/{{ user }}/.local/share/gnome-shell/extensions/simply.workspaces@andyrichardson.dev

- name: Install shade windows
  git:
    repo: https://github.com/andyrichardson/shade-inactive-windows.git
    dest: /home/{{ user }}/.local/share/gnome-shell/extensions/shade-inactive-windows@hepaajan.iki.fi

- name: Load dconf config
  shell: dconf load / < {{ role_path }}/files/dconf.conf
