# intel_iommu
- name: Check for setting
  shell: "grep 'GRUB_CMDLINE_LINUX_DEFAULT=.*intel_iommu=igfx_off.*' /etc/default/grub"
  register: intel_iommu
  failed_when: false
  no_log: true
- name: Set kernel settings
  lineinfile:
    path: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=.*)"'
    line: '\1 intel_iommu=igfx_off"'
  when: intel_iommu.rc == 1
  become: yes

# i915.enable_gvt
- name: Check for setting
  shell: "grep 'GRUB_CMDLINE_LINUX_DEFAULT=.*i915\\.enable_gvt=1.*' /etc/default/grub"
  register: i915_enable_gvt
  failed_when: false
  no_log: true
- name: Set kernel settings
  lineinfile:
    path: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=.*)"'
    line: '\1 i915.enable_gvt=1"'
  when: i915_enable_gvt.rc == 1
  become: yes

# Intel ucode
- name: install apps
  pacman:
    name: intel-ucode
    state: present
  become: yes