- name: Install apps (pacman)
  pacman:
    name:
      - screenkey
  become: yes

- name: install apps (aur)
  kewlfft.aur.aur:
    name: 
      - visual-studio-code-bin
      - google-chrome
      - reaper-bin
    state: present

- name: Add flatpak repo - flathub
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: user

- name: Set flatpak data dirs
  lineinfile:
    path: /etc/environment
    state: present
    regexp: '^XDG_DATA_DIRS='
    line: 'XDG_DATA_DIRS="/usr/local/share/:/usr/share/:/var/lib/flatpak/exports/share/applications:$XDG_DATA_DIRS"'
  become: yes

- name: install apps (flatpak)
  flatpak:
    name:
      - ca.desrt.dconf-editor
      - com.discordapp.Discord
      - com.github.wwmm.easyeffects
      - com.parsecgaming.parsec
      - com.slack.Slack
      # - com.uploadedlobster.peek # broken - https://github.com/phw/peek/issues/748
      - com.valvesoftware.Steam
      - io.github.Figma_Linux.figma_linux
      - io.github.seadve.Kooha
      - org.gimp.GIMP
      - org.gnome.font-viewer
      - org.qbittorrent.qBittorrent
      - org.videolan.VLC
      - rest.insomnia.Insomnia
      - us.zoom.Zoom
      - org.gtk.Gtk3theme.Adwaita-dark
      - https://downloads.1password.com/linux/flatpak/1Password.flatpakref
    state: present
    method: user