- name: install packages
  pacman:
    name: 
     - zsh
     - powerline
    state: present
  become: yes
- stat:
    path: /home/{{ user }}/.antigen
  register: antigen
- name: prepare antigen
  command: mkdir -p /home/{{ user }}/.antigen
  when: antigen.stat.exists == False
- name: install antigen
  shell: curl -L git.io/antigen > /home/{{ user }}/.antigen/antigen.zsh
  when: antigen.stat.exists == False
- name: Add zshrc to home
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "/home/{{ user }}/.zshrc"
    state: link
- name: Add p10k to home
  file:
    src: "{{ role_path }}/files/.p10k.zsh"
    dest: "/home/{{ user }}/.p10k.zsh"
    state: link