import:
  - ~/.alacritty-theme.yml
window:
  startup_mode: Maximized
  decorations: none
cursor:
  style:
    shape: Block
shell:
  program: /usr/bin/tmux
font:
  size: 11
  normal:
    family: "DejaVuSansMono Nerd Font"
