# window:
#   decorations: none
cursor:
  style:
    shape: Block
shell:
  program: /opt/homebrew/bin/tmux
env:
  TERM: xterm-256color
font:
  size: 12
  offset:
    x: 1
    y: 5
  glyph_offset:
    y: 1
  normal:
    family: "DejaVuSansMono Nerd Font"
    style: Book
    antialias: false
key_bindings:
  - {
      key: Comma,
      mods: Command,
      command:
        {
          program: "sh",
          args: ["-c", "open ~/.config/alacritty/alacritty.yml"],
        },
    }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Space, mods: Alt, chars: " " }
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left, mods: Alt, chars: "\x1bb" } # one word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # one word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
  - { key: Return, mods: Shift, chars: "\x1b[13;2u" } # Shift Return (for vim)
  - { key: Return, mods: Control, chars: "\x1b[13;5u" } # Ctrl Return (for vim)
colors:
  # Default colors
  primary:
    background: "0x1e2127"
    foreground: "0xabb2bf"
    bright_foreground: "0xe6efff"

  # Normal colors
  normal:
    black: "0x1e2127"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0x828791"

  # Bright colors
  bright:
    black: "0x5c6370"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xe6efff"

  # Dim colors
  dim:
    black: "0x1e2127"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0x828791"
