- name: install fingerpint driver + howdy
  kewlfft.aur.aur:
    name: 
      - howdy
    state: present

- name: Set howdy camera
  lineinfile:
    path: /usr/lib/security/howdy/config.ini
    regexp: '^device_path'
    line: 'device_path = /dev/video2'
  become: yes