- name: install packages
  pacman:
    name:
      - neovim
    state: present
  become: yes

- name: install python provider
  kewlfft.aur.aur:
    name: python-pynvim
    state: present

- name: Install plugin manager
  shell: sh -c 'curl -fLo /home/{{ user }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  args:
    creates: /home/{{ user }}/.local/share/nvim/site/autoload/plug.vim

- name: Link vim config file (vim)
  file:
    src: "{{ role_path }}/files/.vimrc"
    dest: "/home/{{ user }}/.vimrc"
    state: link

- name: link coc config file
  file:
    src: "{{ role_path }}/files/coc-settings.json"
    dest: "/home/{{ user }}/.config/nvim/coc-settings.json"
    state: link

- name: Create config directory (nvim)
  file:
    dest: "/home/{{ user }}/.config/nvim"
    state: directory

- name: Link vim config file (nvim)
  file:
    src: "{{ role_path }}/files/.vimrc"
    dest: /home/{{ user }}/.config/nvim/init.vim
    state: link

- name: Create coc folder
  file:
    dest: "/home/{{ user }}/.config/coc/extensions"
    state: directory

- name: Install plugins
  shell: |
    source ~/.nvm/nvm.sh
    nvim --headless +PlugInstall +qa
  args:
    creates: /home/{{ user }}/.config/nvim/plugged/coc.nvim
